# Site settings
title: 2010 Versys 650
description: Victoria BC, Canada<br>37000kms<br>Metallic Spark Black<br>non-ABS<br>needs nothing<br>maintenance up to date<br><a href="mailto:VicVersys650@gmail.com">VicVersys650@gmail.com</a><br>$4550<br><a href="https://www.google.ca/maps/place/48°27'17.0%22N+123°28'21.8%22W/@48.454708,-123.4749157,17z/data=!3m1!4b1!4m6!3m5!1s0x0:0x0!7e2!8m2!3d48.4547081!4d-123.4727265">GoogleMaps</a>
baseurl: "/v650" # the subpath of your site, e.g. /blog
url: "https://flexbc.ca" # the base hostname & protocol for your site
author: pw

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
